import json
from typing import Any, Dict, List


RECORDS: List[Dict[str, Any]] = [
    {
        "record_id": "rec_0001",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601010001",
        "pan": "512345******1001",
        "issuer": "Issuer_001",
        "region": "NA",
        "country": "US",
        "currency": "USD",
        "amount": 23.45,
        "merchant": "Coffee Shop A",
        "mcc": "5814",
        "fee_type": "assessment_fee",
        "fee_amount": 0.12,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-01T08:15:00Z",
    },
    {
        "record_id": "rec_0002",
        "investigation_type": "fee_dispute",
        "transaction_id": "TXN202601010002",
        "pan": "512345******1002",
        "issuer": "Issuer_002",
        "region": "NA",
        "country": "US",
        "currency": "USD",
        "amount": 125.0,
        "merchant": "Electronics Mart",
        "mcc": "5732",
        "fee_type": "service_fee",
        "fee_amount": 1.75,
        "status": "billed",
        "anomaly": True,
        "reason_code": "FEE_HIGH",
        "created_at": "2026-01-01T08:20:00Z",
    },
    {
        "record_id": "rec_0003",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601010003",
        "pan": "534321******1003",
        "issuer": "Issuer_001",
        "region": "EU",
        "country": "FR",
        "currency": "EUR",
        "amount": 58.9,
        "merchant": "Bistro Paris",
        "mcc": "5812",
        "fee_type": "interchange_fee",
        "fee_amount": 1.32,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-01T09:05:00Z",
    },
    {
        "record_id": "rec_0004",
        "investigation_type": "rule_violation",
        "transaction_id": "TXN202601010004",
        "pan": "534321******1004",
        "issuer": "Issuer_003",
        "region": "EU",
        "country": "DE",
        "currency": "EUR",
        "amount": 999.99,
        "merchant": "Luxury Goods GmbH",
        "mcc": "5944",
        "fee_type": "foreign_txn_fee",
        "fee_amount": 19.99,
        "status": "billed",
        "anomaly": True,
        "reason_code": "RULE_MISMATCH",
        "created_at": "2026-01-01T09:10:00Z",
    },
    {
        "record_id": "rec_0005",
        "investigation_type": "issuer_level",
        "transaction_id": "TXN202601010005",
        "pan": "545454******1005",
        "issuer": "Issuer_004",
        "region": "AP",
        "country": "JP",
        "currency": "JPY",
        "amount": 12000.0,
        "merchant": "Tokyo Transit",
        "mcc": "4111",
        "fee_type": "processing_fee",
        "fee_amount": 60.0,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-01T10:00:00Z",
    },
    {
        "record_id": "rec_0006",
        "investigation_type": "pan_range",
        "transaction_id": "TXN202601010006",
        "pan": "414720******1006",
        "issuer": "Issuer_005",
        "region": "NA",
        "country": "CA",
        "currency": "CAD",
        "amount": 75.25,
        "merchant": "Grocery North",
        "mcc": "5411",
        "fee_type": "assessment_fee",
        "fee_amount": 0.38,
        "status": "billed",
        "anomaly": True,
        "reason_code": "ASSESSMENT_RATE",
        "created_at": "2026-01-01T10:15:00Z",
    },
    {
        "record_id": "rec_0007",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601010007",
        "pan": "400000******1007",
        "issuer": "Issuer_006",
        "region": "LATAM",
        "country": "BR",
        "currency": "BRL",
        "amount": 210.0,
        "merchant": "Rio Hotel",
        "mcc": "7011",
        "fee_type": "cross_border_fee",
        "fee_amount": 2.1,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-01T10:30:00Z",
    },
    {
        "record_id": "rec_0008",
        "investigation_type": "fee_dispute",
        "transaction_id": "TXN202601010008",
        "pan": "400000******1008",
        "issuer": "Issuer_006",
        "region": "LATAM",
        "country": "BR",
        "currency": "BRL",
        "amount": 49.9,
        "merchant": "Streaming Service",
        "mcc": "4899",
        "fee_type": "service_fee",
        "fee_amount": 3.5,
        "status": "billed",
        "anomaly": True,
        "reason_code": "FEE_UNEXPECTED",
        "created_at": "2026-01-01T10:45:00Z",
    },
    {
        "record_id": "rec_0009",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601010009",
        "pan": "510510******1009",
        "issuer": "Issuer_007",
        "region": "NA",
        "country": "US",
        "currency": "USD",
        "amount": 8.75,
        "merchant": "Parking Meter",
        "mcc": "7523",
        "fee_type": "small_ticket_fee",
        "fee_amount": 0.05,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-01T11:00:00Z",
    },
    {
        "record_id": "rec_0010",
        "investigation_type": "rule_violation",
        "transaction_id": "TXN202601010010",
        "pan": "510510******1010",
        "issuer": "Issuer_007",
        "region": "NA",
        "country": "US",
        "currency": "USD",
        "amount": 2500.0,
        "merchant": "Airline Ticketing",
        "mcc": "4511",
        "fee_type": "interchange_fee",
        "fee_amount": 65.0,
        "status": "billed",
        "anomaly": True,
        "reason_code": "CARD_PRODUCT_MISCLASS",
        "created_at": "2026-01-01T11:10:00Z",
    },
    {
        "record_id": "rec_0011",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601020011",
        "pan": "523456******1011",
        "issuer": "Issuer_008",
        "region": "EU",
        "country": "GB",
        "currency": "GBP",
        "amount": 37.5,
        "merchant": "London Deli",
        "mcc": "5812",
        "fee_type": "foreign_txn_fee",
        "fee_amount": 0.75,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-02T07:15:00Z",
    },
    {
        "record_id": "rec_0012",
        "investigation_type": "fee_dispute",
        "transaction_id": "TXN202601020012",
        "pan": "523456******1012",
        "issuer": "Issuer_008",
        "region": "EU",
        "country": "GB",
        "currency": "GBP",
        "amount": 120.0,
        "merchant": "Online Marketplace",
        "mcc": "5969",
        "fee_type": "dcc_fee",
        "fee_amount": 3.6,
        "status": "billed",
        "anomaly": True,
        "reason_code": "DCC_DISCLOSURE",
        "created_at": "2026-01-02T07:25:00Z",
    },
    {
        "record_id": "rec_0013",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601020013",
        "pan": "601100******1013",
        "issuer": "Issuer_009",
        "region": "NA",
        "country": "US",
        "currency": "USD",
        "amount": 450.0,
        "merchant": "Home Improvement",
        "mcc": "5200",
        "fee_type": "interchange_fee",
        "fee_amount": 8.9,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-02T08:00:00Z",
    },
    {
        "record_id": "rec_0014",
        "investigation_type": "pan_range",
        "transaction_id": "TXN202601020014",
        "pan": "601100******1014",
        "issuer": "Issuer_009",
        "region": "NA",
        "country": "MX",
        "currency": "MXN",
        "amount": 1999.0,
        "merchant": "Resort Cancun",
        "mcc": "7011",
        "fee_type": "cross_border_fee",
        "fee_amount": 19.99,
        "status": "billed",
        "anomaly": True,
        "reason_code": "CROSS_BORDER_MISSING",
        "created_at": "2026-01-02T08:10:00Z",
    },
    {
        "record_id": "rec_0015",
        "investigation_type": "issuer_level",
        "transaction_id": "TXN202601020015",
        "pan": "378282******1015",
        "issuer": "Issuer_010",
        "region": "EU",
        "country": "ES",
        "currency": "EUR",
        "amount": 15.2,
        "merchant": "Metro Tickets",
        "mcc": "4112",
        "fee_type": "processing_fee",
        "fee_amount": 0.09,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-02T09:30:00Z",
    },
    {
        "record_id": "rec_0016",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601020016",
        "pan": "378282******1016",
        "issuer": "Issuer_010",
        "region": "EU",
        "country": "ES",
        "currency": "EUR",
        "amount": 340.0,
        "merchant": "Furniture Store",
        "mcc": "5712",
        "fee_type": "interchange_fee",
        "fee_amount": 6.8,
        "status": "billed",
        "anomaly": True,
        "reason_code": "RATE_TABLE",
        "created_at": "2026-01-02T09:40:00Z",
    },
    {
        "record_id": "rec_0017",
        "investigation_type": "fee_dispute",
        "transaction_id": "TXN202601030017",
        "pan": "356600******1017",
        "issuer": "Issuer_011",
        "region": "AP",
        "country": "IN",
        "currency": "INR",
        "amount": 7999.0,
        "merchant": "Mobile Carrier",
        "mcc": "4814",
        "fee_type": "service_fee",
        "fee_amount": 99.0,
        "status": "billed",
        "anomaly": True,
        "reason_code": "FEE_UNEXPECTED",
        "created_at": "2026-01-03T04:15:00Z",
    },
    {
        "record_id": "rec_0018",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601030018",
        "pan": "356600******1018",
        "issuer": "Issuer_011",
        "region": "AP",
        "country": "IN",
        "currency": "INR",
        "amount": 1200.0,
        "merchant": "Pharmacy",
        "mcc": "5912",
        "fee_type": "assessment_fee",
        "fee_amount": 6.0,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-03T04:20:00Z",
    },
    {
        "record_id": "rec_0019",
        "investigation_type": "rule_violation",
        "transaction_id": "TXN202601030019",
        "pan": "222300******1019",
        "issuer": "Issuer_012",
        "region": "EU",
        "country": "IT",
        "currency": "EUR",
        "amount": 180.0,
        "merchant": "Car Rental",
        "mcc": "7512",
        "fee_type": "late_fee",
        "fee_amount": 35.0,
        "status": "billed",
        "anomaly": True,
        "reason_code": "ACCOUNT_STATUS",
        "created_at": "2026-01-03T06:00:00Z",
    },
    {
        "record_id": "rec_0020",
        "investigation_type": "single_transaction",
        "transaction_id": "TXN202601030020",
        "pan": "222300******1020",
        "issuer": "Issuer_012",
        "region": "EU",
        "country": "IT",
        "currency": "EUR",
        "amount": 42.0,
        "merchant": "Gelato Shop",
        "mcc": "5814",
        "fee_type": "interchange_fee",
        "fee_amount": 0.88,
        "status": "billed",
        "anomaly": False,
        "reason_code": None,
        "created_at": "2026-01-03T06:05:00Z",
    },
]

# Generate remaining records with different combinations
for i in range(21, 51):
    region = ["NA", "EU", "AP", "LATAM"][i % 4]
    country = {"NA": ["US", "CA"], "EU": ["DE", "FR", "GB"], "AP": ["JP", "SG", "AU"], "LATAM": ["BR", "MX"]}[region][i % 2]
    currency = {"US": "USD", "CA": "CAD", "DE": "EUR", "FR": "EUR", "GB": "GBP", "JP": "JPY", "SG": "SGD", "AU": "AUD", "BR": "BRL", "MX": "MXN"}[country]
    inv_type = ["single_transaction", "fee_dispute", "pan_range", "issuer_level", "rule_violation"][i % 5]
    fee_type = ["interchange_fee", "assessment_fee", "service_fee", "cross_border_fee", "foreign_txn_fee", "processing_fee"][i % 6]
    mcc = ["5411", "5812", "5732", "7011", "4511", "5969", "4899"][i % 7]
    anomaly = i % 6 in (0, 1)
    reason_code = None if not anomaly else ["RATE_TABLE", "RULE_MISMATCH", "FEE_HIGH", "CROSS_BORDER_MISSING", "ACCOUNT_STATUS"][i % 5]

    RECORDS.append(
        {
            "record_id": f"rec_{i:04d}",
            "investigation_type": inv_type,
            "transaction_id": f"TXN202601{i:02d}{i:04d}",
            "pan": f"{500000 + i:06d}******{1000 + i:04d}",
            "issuer": f"Issuer_{(i % 15) + 1:03d}",
            "region": region,
            "country": country,
            "currency": currency,
            "amount": round((i * 17.35) % 3500 + 5.0, 2),
            "merchant": f"Merchant_{i:03d}",
            "mcc": mcc,
            "fee_type": fee_type,
            "fee_amount": round(((i * 0.37) % 25) + (0.05 if fee_type == "assessment_fee" else 0.5), 2),
            "status": "billed" if i % 9 != 0 else "reversed",
            "anomaly": anomaly,
            "reason_code": reason_code,
            "created_at": f"2026-01-{(i % 28) + 1:02d}T{(i % 24):02d}:{(i * 3) % 60:02d}:00Z",
        }
    )


def get_records() -> List[Dict[str, Any]]:
    return list(RECORDS)


def get_records_json(indent: int = 2) -> str:
    return json.dumps(RECORDS, indent=indent)
